# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
 - group: SONAR
 - name: APP_NAME
   value: cart

resources:
  repositories:
    - repository: templates
      type: git
      name: ci-build-templates

steps:

  - template: nodejs.yml@templates